In [1]:
import numpy as np
from scipy.special import softmax as sp_softmax
from  f_similarity_metrics import softmax

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([[3, 14, 15, 6],
              [17, 5, 19, 20],
              [21, 4, 4, 24]])

print("our")
print(softmax(a))

print("scipy")
print (sp_softmax(a, axis=1))

print(f"{softmax(a,axis=1)-sp_softmax(a, axis=1)}")






our
[[0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]]
scipy
[[0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]
 [0.0320586  0.08714432 0.23688282 0.64391426]]
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00 -1.38777878e-17 -2.77555756e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.11022302e-16]]


In [2]:
#create a datafrme dove ogni riga è un vettore di probabilità
import pandas as pd
import numpy as np
import random
import numpy as np
from scipy.special import softmax as sp_softmax
from scipy.stats import entropy as shannon_entropy
from scipy.spatial.distance import jensenshannon as sp_jensenshannon
x_df=pd.DataFrame(np.random.rand(3,10))
query= x_df.loc[1].to_numpy().reshape(1, -1)
print(x_df)
print("query")
print(query)
query_complexity=np.exp(shannon_entropy(query,axis=1))

#get teh number form query_complexity

print(query_complexity)

row=x_df.loc[2]

data_vec=row.to_numpy().reshape(1, -1)[0]
sum_pos= query+data_vec
mean_pos=sum_pos/(2.0)
complexity_pos_num=np.exp(shannon_entropy(mean_pos, axis=1))[0]
complexity_pos_product_den=query_complexity*np.exp(1)
score_pos= 2- complexity_pos_num/ np.sqrt(complexity_pos_product_den)

test=[]
print (score_pos)
test.append(score_pos)
print(test)
test.append(score_pos)
print(test)
out=np.array(test)
print(out)
out.shape


          0         1         2         3         4         5         6  \
0  0.617326  0.309619  0.464346  0.940438  0.572926  0.094445  0.479886   
1  0.935192  0.574756  0.666453  0.844347  0.778913  0.285554  0.627502   
2  0.836444  0.025213  0.649259  0.072438  0.080643  0.222172  0.865214   

          7         8         9  
0  0.084813  0.899895  0.466613  
1  0.175216  0.620349  0.612054  
2  0.013143  0.185981  0.730399  
query
[[0.93519195 0.5747563  0.66645272 0.84434692 0.77891299 0.28555353
  0.62750201 0.17521602 0.62034884 0.6120543 ]]
[9.2701356]
[0.24032188]
[array([0.24032188])]
[array([0.24032188]), array([0.24032188])]
[[0.24032188]
 [0.24032188]]


(2, 1)

In [2]:
# from scipy.spatial.distance import jensenshannon as sp_jensenshannon
# from f_similarity_metrics import jensenshannon

# a=softmax(a,axis=1)
# b=softmax(b,axis=1)
# print("a=",a)
# print("b=",b)
# print("sp_jensenshannon")
# print(sp_jensenshannon(a, b,axis=1, keepdims=True)**2)
# print("ours")
# print(jensenshannon(a, b, axis=1))
# print("diff")
# print(f"{jensenshannon(a, b,axis=1)-(sp_jensenshannon(a, b,axis=1,keepdims=True)**2)}")


ImportError: cannot import name 'jensenshannon' from 'f_similarity_metrics' (/home/francescascotti/dev/relevance_feedback/fun_experiments/f_similarity_metrics.py)

In [30]:
#create a datafrme dove ogni riga è un vettore di probabilità
import pandas as pd
import numpy as np
import random
import numpy as np
from scipy.special import softmax as sp_softmax
from scipy.spatial.distance import jensenshannon as sp_jensenshannon
import time
from scipy.stats import entropy

def jensenshannon(x, y):
    '''
    Parameters:
    x: input probabilistic array
    y: input probabilistic array
    Returns:
    jensenshannon: Jensen-Shannon divergence along each axis-slice of  the two input arrays

    '''
   # Compute the average of the two arrays
    avg = (x + y) / 2
    # Compute the shannon_entropy of the average array
    shannonentropy_of_avg = entropy(avg)
    #compute the average of the shannon_entropy of the two arrays
    avg_of_shannonentropy = (entropy(x) + entropy(y)) / 2.0
    
    return  (shannonentropy_of_avg-avg_of_shannonentropy)

def jensen_shannon_matrix(x_df, y_df):
    if isinstance(x_df, np.ndarray):
        x_matrix = x_df
    else:
        x_matrix = x_df.values

    if isinstance(y_df, np.ndarray):
        y_matrix = y_df
    else:
        y_matrix = y_df.values

    results = np.zeros((x_matrix.shape[0], y_matrix.shape[0]))
    
    for i in range(x_matrix.shape[0]):
        for j in range(y_matrix.shape[0]):
            results[i, j] = jensenshannon(x_matrix[i], y_matrix[j])
            
    return results

def sp_jensen_shannon_matrix(x_df, y_df):
    if isinstance(x_df, np.ndarray):
        x_matrix = x_df
    else:
        x_matrix = x_df.values

    if isinstance(y_df, np.ndarray):
        y_matrix = y_df
    else:
        y_matrix = y_df.values

    results = np.zeros((x_matrix.shape[0], y_matrix.shape[0]))
    
    for i in range(x_matrix.shape[0]):
        for j in range(y_matrix.shape[0]):
            results[i, j] = sp_jensenshannon(x_matrix[i], y_matrix[j])
            
    return results

def sp_squared_jensen_shannon_matrix(x_df, y_df):
    if isinstance(x_df, np.ndarray):
        x_matrix = x_df
    else:
        x_matrix = x_df.values

    if isinstance(y_df, np.ndarray):
        y_matrix = y_df
    else:
        y_matrix = y_df.values

    results = np.zeros((x_matrix.shape[0], y_matrix.shape[0]))
    
    for i in range(x_matrix.shape[0]):
        for j in range(y_matrix.shape[0]):
            results[i, j] = sp_jensenshannon(x_matrix[i], y_matrix[j])**2
            
    return results
def old_sed(x, y):
    '''
    Parameters:
    x: input probabilistic array 
    y: input probabilistic array 
    Returns:
    sed: symmetric entropy distance between the two input arrays
    '''
    # Compute the average of the two arrays
    avg = (x + y) / 2
    # Compute the complexity of the average array
    complexity_avg = complexity(avg)
    # Compute the product of the complexity of the two arrays
    complexity_product = (complexity(x) * complexity(y)) ** (1 / 2)
    # Compute the symmetric entropy distance
    sed = complexity_avg / complexity_product
    return sed-1

def complexity(x):
    '''
    Parameters:
    x: input probabilistic array 
    Returns:
    complexity: complexity of the input array
    '''
    return np.exp(shannon_entropy(x))

def shannon_entropy(x):
    '''
    Parameters:
    x: input probabilistic array 
    Returns:
    shannon_entropy: shared entropy of the input array
    '''
    y= np.where(x == 0, 1, x)  # Replace zero or negative values with epsilon
    ##shall we do #epsilon = 1e-10  # Small epsilon to avoid zero or negative values y= np.where(x < epsilon, 1, x)  # x = np.where(x <= 0, epsilon, x)  # Replace zero or negative values with epsilon
    if np.any(y <= 0):
        raise ValueError("Invalid values encountered in input array x")
    log_x = np.log(y)
    shannon_entropy = -np.sum(x * log_x)
    return shannon_entropy

def sed(x, y):
    '''
    Parameters:
    x: input probabilistic array 
    y: input probabilistic array 
    Returns:
    sed: symmetric entropy distance along each axis-slice of x  the two input arrays
    '''
    return np.exp(jensenshannon(x,y))-1
def sed_matrix(x_df, y_df):
    if isinstance(x_df, np.ndarray):
        x_matrix = x_df
    else:
        x_matrix = x_df.values

    if isinstance(y_df, np.ndarray):
        y_matrix = y_df
    else:
        y_matrix = y_df.values

    results = np.zeros((x_matrix.shape[0], y_matrix.shape[0]))
    
    for i in range(x_matrix.shape[0]):
        for j in range(y_matrix.shape[0]):
            results[i, j] = sed(x_matrix[i], y_matrix[j])
            
    return results

def old_sed_matrix(x_df, y_df):
    if isinstance(x_df, np.ndarray):
        x_matrix = x_df
    else:
        x_matrix = x_df.values

    if isinstance(y_df, np.ndarray):
        y_matrix = y_df
    else:
        y_matrix = y_df.values

    results = np.zeros((x_matrix.shape[0], y_matrix.shape[0]))
    
    for i in range(x_matrix.shape[0]):
        for j in range(y_matrix.shape[0]):
            results[i, j] = old_sed(x_matrix[i], y_matrix[j])
            
    return results
x_df=pd.DataFrame(np.random.rand(2,10))
y_df=pd.DataFrame(np.random.rand(2,10))

#apply softmax at each row of x_df
x_df=x_df.apply(sp_softmax,axis=1)
#apply softmax at each row of y_df
y_df=y_df.apply(sp_softmax,axis=1)
print(x_df.shape)

#print("x_df=\n",x_df, "\n shape=",x_df.shape)
#print("y_df=\n",y_df,"\n shape=",y_df.shape)
#time to cumpute the jensen shannon distance
print("sp_jensenshannon")
startms = time.time()
scipy_js=sp_jensen_shannon_matrix(x_df, y_df)
endms = time.time()
print(f"-->sp_js matrix={scipy_js}")
#print shape of the matrix
print(f"shape={scipy_js.shape}")
print(f"sp_jensenshannon time={endms-startms}")

print("scipy squared jensenshannon")
startms = time.time()
scipy_js_sq=sp_squared_jensen_shannon_matrix(x_df, y_df)
endms = time.time()
print(f"-->scipy_js_sq matrix={scipy_js_sq}")
print(f"shape={scipy_js_sq.shape}")
print(f"scipy squared jensenshannon time={endms-startms}")

print("ours")
startms = time.time()
our_js=jensen_shannon_matrix(x_df, y_df )
endms = time.time()
print(f"-->our_js matrix={our_js}")
print(f"shape={our_js.shape}")

print(f"our_js time={endms-startms}")

scipy_js2=scipy_js**2
print ("-->scipy_js**2=",scipy_js2)
print ("shape=",(scipy_js2).shape)  

print("**")


print("diff")


#print(f"our_js-scipy_js: {(our_js-scipy_js).max()}")
print(f"our_js-scipy_js_sq: {(our_js-scipy_js_sq).max()}")

print(f"our_js-scipy_js**2 {(our_js-(scipy_js2)).max()}")
print(f"scipy_js**2 -scipy_js_sq{((scipy_js2 )-scipy_js_sq).max()}")

# print("sp_jensenshannon")
# print(jensen_shannon_matrix(x_df, y_df )**2)
# print("ours")
# print(jensen_shannon_matrix_test(x_df, y_df ))
# print("diff")
# print(f"{jensen_shannon_matrix_test(x_df, y_df)-(jensen_shannon_matrix(x_df, y_df)**2)}")

#old sed
print("old sed")
startms = time.time()
old_sed=old_sed_matrix(x_df, y_df)
endms = time.time()
print(f"-->old_sed matrix={old_sed}")
print(f"shape={old_sed.shape}")
print(f"old_sed time={endms-startms}")

print("ours")
startms = time.time()
our_sed=sed_matrix(x_df, y_df)
endms = time.time()
print(f"-->our_sed matrix={our_sed}")
print(f"shape={our_sed.shape}")
print(f"our_sed time={endms-startms}")

print("diff")
print(f"our_sed-old_sed: {(our_sed-old_sed).max()}")





(2,)
sp_jensenshannon
-->sp_js matrix=[[0.11861471 0.14864107]
 [0.15981315 0.16941605]]
shape=(2, 2)
sp_jensenshannon time=0.0003063678741455078
scipy squared jensenshannon
-->scipy_js_sq matrix=[[0.01406945 0.02209417]
 [0.02554024 0.0287018 ]]
shape=(2, 2)
scipy squared jensenshannon time=0.00028967857360839844
ours
-->our_js matrix=[[0.01406945 0.02209417]
 [0.02554024 0.0287018 ]]
shape=(2, 2)
our_js time=0.005854606628417969
-->scipy_js**2= [[0.01406945 0.02209417]
 [0.02554024 0.0287018 ]]
shape= (2, 2)
**
diff
our_js-scipy_js_sq: 5.863365348801608e-16
our_js-scipy_js**2 5.863365348801608e-16
scipy_js**2 -scipy_js_sq0.0
old sed
-->old_sed matrix=[[0.01416889 0.02234005]
 [0.02586919 0.02911766]]
shape=(2, 2)
old_sed time=0.0005488395690917969
ours
-->our_sed matrix=[[0.01416889 0.02234005]
 [0.02586919 0.02911766]]
shape=(2, 2)
our_sed time=0.005562305450439453
diff
our_sed-old_sed: 2.220446049250313e-16
